config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define the root path route ("/")
  # root "articles#index"
  resources :foods, only: [:index, :show, :new, :create, :destroy]

  authenticated :user do
    root 'recipes#index', as: :authenticated_root
  end

  root 'home#index'

  resources :recipes do
    member do
      delete :destroy
      patch :toggle_recipe_public
      get 'add_ingredient', to: 'recipes#add_ingredient'
      post 'add_ingredient', to: 'recipes#add_ingredient'
      get 'generate_shopping_list', to: 'recipes#generate_shopping_list'
      delete 'remove_food'
    end

    collection do
      get 'public_recipes', to: 'recipes#public_recipes'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods
  has_many :foods, through: :recipe_foods

  attribute :public, :boolean, default: false
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :recipes, dependent: :destroy
  has_many :foods, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  helper_method :current_user
  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name, :email, :password, :password_confirmation)
    end
  end

  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @foods = Food.all
  end

  def new
    @user = current_user
    @food = Food.new
  end

  def show
    @food = Food.find(params[:id])
  end

  def destroy
    puts 'Destroy action called'
    @food = Food.find(params[:id])
    if @food.user == current_user
      @food.destroy
      redirect_to foods_path, notice: 'Food deleted successfully!'
    else
      redirect_to foods_path, alert: 'You do not have permission to delete this food item.'
    end
  end

  def create
    @user = current_user
    @food = current_user.foods.build(food_params)
    @food.user_id = current_user.id
    if @food.save
      redirect_to foods_path(@user), notice: 'Food was successfully added.'
    else
      render :new
    end
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def index
    @recipes = current_user.recipes.includes(:foods)
  end

  def new
    @recipe = Recipe.new
  end

  def add_ingredient
    @recipe = Recipe.find(params[:id])

    if current_user == @recipe.user
      @foods_not_in_recipe = Food.where.not(id: @recipe.foods.pluck(:id))

      if params[:recipe].present? && params[:recipe][:food_ids].present?
        food_ids = params[:recipe][:food_ids].reject(&:empty?) # Remove empty strings
        @recipe.foods << Food.where(id: food_ids)
        flash[:notice] = 'Ingredients added successfully.'
        redirect_to @recipe
        return
      end
    else
      flash[:alert] = 'You do not have permission to add ingredients to this recipe.'
    end

    render 'add_ingredient'
  end

  def remove_food
    @recipe = Recipe.find(params[:id])
    @food = Food.find(params[:food_id])
    if current_user == @recipe.user
      @recipe.foods.delete(@food)
      flash[:notice] = 'Ingredient removed successfully.'
    else
      flash[:alert] = 'You do not have permission to remove ingredients from this recipe.'
    end
    redirect_to @recipe
  end

  def public_recipes
    @public_recipes = Recipe.where(public: true).includes(:foods)
    @total_food_items = Food.joins(:recipe_foods).where(recipe_foods: { recipe_id: @public_recipes.pluck(:id) }).sum(:quantity)
    @total_price = Food.joins(:recipe_foods).where(recipe_foods: { recipe_id: @public_recipes.pluck(:id) }).sum('foods.quantity * foods.price')
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      flash[:notice] = 'Recipe created successfully.'
      redirect_to recipe_path(@recipe)
    else
      flash.now[:alert] = 'Recipe creation failed.'
      redirect_to new_recipe_url
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.user == current_user
      @recipe.recipe_foods.destroy_all

      @recipe.destroy
      flash[:notice] = 'Recipe deleted successfully.'
    else
      flash[:alert] = 'You do not have permission to delete this recipe.'
    end
    redirect_to recipes_path
  end

  def show
    @recipe = Recipe.find(params[:id])
    @toggle_recipe_public = params[:toggle_recipe_public]
    return unless @toggle_recipe_public && @recipe.user == current_user

    @recipe.update(public: !@recipe.public)
    flash[:notice] = @recipe.public ? 'Recipe is now public.' : 'Recipe is now private.'
    redirect_to recipe_path(@recipe)
  end

  def toggle_recipe_public
    @recipe = Recipe.find(params[:id])

    if @recipe.user == current_user
      @recipe.update(public: !@recipe.public)
      flash[:notice] = @recipe.public ? 'Recipe is now public.' : 'Recipe is now private.'
    else
      flash[:alert] = 'You do not have permission to toggle this recipe.'
    end

    redirect_to @recipe
  end

  def generate_shopping_list
    @recipe = Recipe.find(params[:id])

    @required_foods = @recipe.foods.where.not(user: current_user).includes(:user)
    @total_value = @required_foods.sum { |food| food.quantity * food.price }
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/index.html.erb
<div class="recipe-index">
<h2> Food List </h2>
<%= link_to 'Add New Food', new_food_path, class: 'btn btn-primary' %>
<br/>
<br>
<table class="table table-stripped table-bordered table-hover table-success">
  <thead class="table-light"> 
    <tr>
      <th>Name</th>
      <th>Measurement Unit</th>
      <th>Unit Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @foods.includes(:user).each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= food.price %></td>
        <td>
          <% if food.user == current_user %>
            <%= form_with(model: food, method: :delete, local: true, data: { confirm: 'Are you sure?' }) do |form| %>
              <%= form.submit 'Remove Food', class: 'btn btn-danger' %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/foods/new.html.erb
<div class="recipe-index">
<h1>Add New Food</h1>
<%= form_with(model: @food, url: foods_path) do |form| %>
  <div class="field form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  
   <div class="field form-group">
    <%= form.label :measurement_unit, style: "display: block"%>
    <%= form.text_field :measurement_unit %>
  </div>

   <div class="field form-group">
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div class="field form-group">
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>
    <br>
  <div class="actions">
    <%= form.submit 'Add Food', class: "btn btn-secondary"%>
  </div>
<% end %>
</div>

app/views/foods/show.html.erb
<h1>Food Details</h1>

<table class="table">
  <tbody>
    <tr>
      <th>Name:</th>
      <td><%= @food.name %></td>
    </tr>
    <tr>
      <th>Measurement Unit:</th>
      <td><%= @food.measurement_unit %></td>
    </tr>

    <tr>
      <th>Unit Price:</th>
      <td><%= @food.price %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Back to Food List', foods_path, class: 'btn btn-primary' %>

app/views/home/_header.html.erb
<nav class="custom-navbar">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "RecipeApp", root_path, class: "navbar-brand custom-brand" %>
    </div>
    <div class="menu-button">
      <span class="menu-icon">&#9776;</span>
    </div>
    <div class="navbar-menu">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Foods", foods_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Food", new_food_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Recipes", recipes_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Public Recipes", public_recipes_recipes_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link custom-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link custom-link" %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="mobile-menu">
      <ul class="navbar-nav">
          <div class="close-button">
            <span class="close-icon">&times;</span>
          </div>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Foods", foods_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Add Food", new_food_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Recipes", recipes_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Public Recipes", public_recipes_recipes_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link custom-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link custom-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link custom-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="welcome-container">
  <div class="welcome-content">
    <h1 class="welcome-heading">Welcome to RecipeApp</h1>
    <p class="welcome-text">Discover a World of Delicious Recipes</p>
    <a href="<%= recipes_path %>" class="btn btn-primary explore-button">Explore Recipes</a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', 'recipe' %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
    <script>
      document.addEventListener('turbo:load', function () {
          const menuButton = document.querySelector(".menu-button");
          const menu = document.querySelector(".mobile-menu");
          const closeButton = document.querySelector('.close-button');
          function openMenu() {
            menu.classList.add('open');
            menuButton.style.display = 'none';
            closeButton.style.display = 'block';
          }

          function closeMenu() {
            menu.classList.remove('open');
            closeButton.style.display = 'none';
            menuButton.style.display = 'block';
          }
          menuButton.addEventListener('click', openMenu);
          closeButton.addEventListener('click', closeMenu);
        });
    </script>
  </head>

  <body>

  <%= render "home/header" %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/recipes/_add_ingredient_form.html.erb
<h3>Add Ingredient</h3>
<%= form_for @recipe, url: add_ingredient_recipe_path(@recipe), method: :post do |f| %>
  <div class="form-group">
    <%= f.label :food_ids, 'Select Ingredient' %>
    <%= f.collection_select :food_ids, @foods_not_in_recipe, :id, :name, {}, multiple: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'Add Ingredients', class: 'btn btn-primary' %>
  </div>
<% end %>

<script>
  function removeEmptyValues() {
    const selectElement = document.querySelector("#recipe_food_ids");
    const selectedOptions = Array.from(selectElement.selectedOptions);

    // Remove empty values ("" is empty)
    const filteredSelectedValues = selectedOptions.map(option => option.value).filter(value => value !== "");

    // Update the form field with the filtered values
    selectElement.value = filteredSelectedValues;
  }
</script>

app/views/recipes/add_ingredient.html.erb
<div class="recipe-show-page">
  <div class="recipe-header">
    <h2><%= @recipe.name %></h2>
  </div>

  <div id="add-ingredient-form">
    <%= render 'add_ingredient_form' %>
  </div>
</div>

app/views/recipes/generate_shopping_list.html.erb
<div class="shopping-list">
  <h2 class="section-title">Generate Shopping List</h2>
  <div class="shopping-list-summary">
    <div class="summary-item">
      <p>Amount of food items to buy: <%= @required_foods.count %></p>
    </div>
    <div class="summary-item">
      <p>Total Value of food needed: <%= number_to_currency(@total_value) %></p>
    </div>
  </div>

  <h3 class="section-subtitle">Required Food Items</h3>
  <table class="shopping-list-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Measurement Unit</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @required_foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.quantity %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= number_to_currency(food.price * food.quantity) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Back to Recipe', recipe_path(@recipe), class: 'back-button' %>
</div>

app/views/recipes/index.html.erb
<div class="recipe-index">
<h2>Your Recipes</h2>
<div class="recipes-container">
  <ul class="recipe-list">
    <% @recipes.each do |recipe| %>
      <li class="recipe-item">
          <%= link_to recipe.name, recipe_path(recipe), class: 'recipe-name' %>
          <p class="recipe-description"><%= recipe.description %></p>    
          <% if recipe.user == current_user %>
            <%= form_with(model: recipe, method: :delete, local: true, data: { confirm: 'Are you sure?' }) do |form| %>
            <%= form.submit 'Delete', class: 'btn btn-danger btn-sm' %>
            <% end %>
          <% end %>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to 'New Recipe', new_recipe_path, class: 'btn btn-primary' %>
</div>

app/views/recipes/new.html.erb
<div class="recipe-index">
<h2>Create a New Recipe</h2>
<div class="container-login">
<%= form_with(model: @recipe, local: true) do |form| %>
  <div class="mb-3">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :preparation_time, class: 'form-label' %>
    <%= form.number_field :preparation_time, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :cooking_time, class: 'form-label' %>
    <%= form.number_field :cooking_time, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: 'form-label' %>
    <%= form.text_area :description, class: 'form-control', required: true %>
  </div>

  <div class="mb-3">
    <%= form.label :public, class: 'form-label' %>
    <%= form.check_box :public, class: 'form-check-input' %>
  </div>

  <%= form.submit 'Create Recipe', class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Back to Recipes', recipes_path %>
</div>

app/views/recipes/public_recipes.html.erb
<div class="recipe-index">
  <h1 class="section-title">Public Recipes</h1>

  <div class="recipe-list">
    <% @public_recipes.each do |recipe| %>
      <div class="recipe-card">
        <div class="recipe-details">
          <h2 class="recipe-name"><%= recipe.name %></h2>
          <p class="recipe-author">By: <%= recipe.user.name %></p>
        </div>
        <div class="recipe-stats">
          <p class="recipe-info">Total Food Items: <%= @total_food_items %></p>
          <p class="recipe-info">Total Price: $<%= @total_price %></p>
          <a href="<%= recipe_path(recipe) %>" class="view-details-button">View Details</a>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="recipe-show-page">
  <div class="recipe-header">
    <h2><%= @recipe.name %></h2>
    <div class="top-line">
      <p>Preparation Time: <%= @recipe.preparation_time %> minutes</p>
      <p>
        <% if current_user == @recipe.user %>
          <% if @recipe.public %>
            <%= link_to 'Make Private', recipe_path(@recipe, toggle_recipe_public: true), method: :patch, class: 'btn btn-primary btn-sm' %>
          <% else %>
            <%= link_to 'Make Public', recipe_path(@recipe, toggle_recipe_public: true), method: :patch, class: 'btn btn-primary btn-sm' %>
          <% end %>
        <% end %>
      </p>
    </div>
  </div>
  <p>Cooking Time: <%= @recipe.cooking_time %> minutes</p>
  <p class="recipe-description">Description: <%= @recipe.description %></p>

  <h3>Required Food Items</h3>
  <div class="recipe-show-button-container">
    <%= link_to 'Generate Shopping List', generate_shopping_list_recipe_path(@recipe), class: 'btn btn-primary' %>
    <% if current_user == @recipe.user %>      
      <%= link_to 'Add Ingredient', add_ingredient_recipe_path(@recipe), class: 'btn btn-primary' %>
    <% end %>
  </div>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Quantity</th>
        <th>Measurement Unit</th>
        <th>Price</th>
        <th>Action</th> <!-- Add an Action column -->
      </tr>
    </thead>
    <tbody>
      <% @recipe.foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.quantity %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= number_to_currency(food.price) %></td>
          <td>
            <% if current_user == @recipe.user %>
              <%= form_tag(remove_food_recipe_path(@recipe, food_id: food.id), method: :delete) do %>
                <%= submit_tag 'Remove Food', class: 'btn btn-danger btn-sm' %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Back to Recipes', recipes_path, class: 'btn btn-secondary' %>
</div>